# Generated by Django 4.0.4 on 2022-05-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porfolio',
            new_name='Proyecto',
        ),
    ]
